plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'duke.Wangsa'
}

tasks.named('run', JavaExec) {
    standardInput = System.in
}

tasks.named('test', Test) {
    useJUnitPlatform()
}
